// Auto-generated by scripts/reporting/generate-whats-new.mjs
// Do not edit manually.

export interface WhatsNewEntry {
  date: string;
  sortDate: string;
  title: string;
  description: string;
}

export const WHATS_NEW: WhatsNewEntry[] = [
  {
    date: "Mar 21",
    sortDate: "2026-03-21",
    title: "Update whats new entry",
    description: "Code updates shipped in commit 83867d9.",
  },
  {
    date: "Mar 21",
    sortDate: "2026-03-21",
    title: "Simplify admin shell and dashboard",
    description: "Code updates shipped in commit 740f612.",
  },
  {
    date: "Mar 21",
    sortDate: "2026-03-21",
    title: "Fill Q3 daily goals from reporting data",
    description: "Code updates shipped in commit a949612.",
  },
  {
    date: "Mar 10",
    sortDate: "2026-03-10",
    title: "Fix curriculum map dropdown behavior",
    description: "Code updates shipped in commit 783d359.",
  },
  {
    date: "Mar 6",
    sortDate: "2026-03-06",
    title: "convex fixes",
    description: "Code updates shipped in commit 80dc703.",
  },
  {
    date: "Mar 5",
    sortDate: "2026-03-05",
    title: "Lib changed from present to review",
    description: "Code updates shipped in commit 054d19e.",
  },
  {
    date: "Mar 5",
    sortDate: "2026-03-05",
    title: "docs updated",
    description: "Code updates shipped in commit f45f1a3.",
  },
  {
    date: "Mar 5",
    sortDate: "2026-03-05",
    title: "Confirm AI link updates",
    description: "Code updates shipped in commit 0e4e72f.",
  },
  {
    date: "Feb 19",
    sortDate: "2026-02-19",
    title: "Add student diagnostic review page and harden retake submit flow",
    description: "Code updates shipped in commit 31e2d63.",
  },
  {
    date: "Feb 19",
    sortDate: "2026-02-19",
    title: "Add sleepy low-energy check-in option",
    description: "Code updates shipped in commit 519b1a0.",
  },
  {
    date: "Feb 18",
    sortDate: "2026-02-18",
    title: "Allow admins to view password inputs in settings",
    description: "Code updates shipped in commit 8878e58.",
  },
  {
    date: "Feb 17",
    sortDate: "2026-02-17",
    title: "chore: refresh generated whats-new feed",
    description: "Code updates shipped in commit e3ee3a5.",
  },
  {
    date: "Feb 17",
    sortDate: "2026-02-17",
    title: "fix(ui): replace comment icon with cleaner chat glyph",
    description: "Code updates shipped in commit ed2e83f.",
  },
  {
    date: "Feb 17",
    sortDate: "2026-02-17",
    title: "chore: refresh generated whats-new feed",
    description: "Code updates shipped in commit 782ef8e.",
  },
  {
    date: "Feb 17",
    sortDate: "2026-02-17",
    title: "fix(ui): improve sidebar comment action affordance",
    description: "Code updates shipped in commit 41bcf4e.",
  },
  {
    date: "Feb 17",
    sortDate: "2026-02-17",
    title: "docs(agent): add postmortem and mandatory build/deploy gates",
    description: "Code updates shipped in commit 4c8cfa3.",
  },
  {
    date: "Feb 17",
    sortDate: "2026-02-17",
    title: "chore: refresh generated whats-new feed",
    description: "Code updates shipped in commit 022ba5f.",
  },
  {
    date: "Feb 17",
    sortDate: "2026-02-17",
    title: "fix: resolve netlify production build type errors",
    description: "Code updates shipped in commit b146273.",
  },
  {
    date: "Feb 17",
    sortDate: "2026-02-17",
    title: "docs: streamline agent routing and simplify repository documentation",
    description: "Code updates shipped in commit 32c93c0.",
  },
  {
    date: "Feb 17",
    sortDate: "2026-02-17",
    title: "chore: simplify docs and align app behavior updates",
    description: "Code updates shipped in commit 49c6f80.",
  },
  {
    date: "Feb 17",
    sortDate: "2026-02-17",
    title: "Polish sidebar comment and sign out action styling",
    description: "Code updates shipped in commit 930df8f.",
  },
  {
    date: "Feb 17",
    sortDate: "2026-02-17",
    title: "Include own student profile in friend profiles query",
    description: "Code updates shipped in commit c2e0e72.",
  },
  {
    date: "Feb 14",
    sortDate: "2026-02-14",
    title: "Add admin sprint student goal insights dashboard",
    description: "Code updates shipped in commit 1b927a2.",
  },
  {
    date: "Feb 13",
    sortDate: "2026-02-13",
    title: "Refine Viva Queue empty states for clearer layout",
    description: "Code updates shipped in commit 497414a.",
  },
  {
    date: "Feb 13",
    sortDate: "2026-02-13",
    title: "Improve Viva review clarity and attempts metrics",
    description: "Code updates shipped in commit 1bd06ae.",
  },
  {
    date: "Feb 13",
    sortDate: "2026-02-13",
    title: "Fix student comment widget overlap across pages",
    description: "Code updates shipped in commit 9ed1870.",
  },
  {
    date: "Feb 13",
    sortDate: "2026-02-13",
    title: "Automate in-app What's New from git history",
    description: "Code updates shipped in commit bb8ca1f.",
  },
  {
    date: "Feb 13",
    sortDate: "2026-02-13",
    title: "Add viva batch toggle and friend GIF expansion in settings",
    description: "Code updates shipped in commit 63fd321.",
  },
  {
    date: "Feb 12",
    sortDate: "2026-02-12",
    title: "Refine diagnostic question flow and last-question skip",
    description: "Code updates shipped in commit e6e1ed1.",
  },
  {
    date: "Feb 12",
    sortDate: "2026-02-12",
    title: "Improve diagnostic review clarity and add question skip flow",
    description: "Code updates shipped in commit 770c5c7.",
  },
];

export default WHATS_NEW;
