# Serena Project Configuration
project_name: "DW"

# Use 'language: x' for single language, or 'languages:' array for multiple
languages:
- typescript

ignore_all_files_in_gitignore: true
ignored_paths: []
read_only: false
excluded_tools: []
included_optional_tools: []
initial_prompt: ""
encoding: utf-8
