/* eslint-disable */
// Auto-generated by scripts/generate-whats-new.mjs
// Do not edit manually.

export interface WhatsNewEntry {
  date: string;
  sortDate: string;
  title: string;
  description: string;
}

export const WHATS_NEW: WhatsNewEntry[] = [
  {
    date: "Feb 17",
    sortDate: "2026-02-17",
    title: "fix(ui): improve sidebar comment action affordance",
    description: "Code updates shipped in commit 41bcf4e.",
  },
  {
    date: "Feb 17",
    sortDate: "2026-02-17",
    title: "docs(agent): add postmortem and mandatory build/deploy gates",
    description: "Code updates shipped in commit 4c8cfa3.",
  },
  {
    date: "Feb 17",
    sortDate: "2026-02-17",
    title: "chore: refresh generated whats-new feed",
    description: "Code updates shipped in commit 022ba5f.",
  },
  {
    date: "Feb 17",
    sortDate: "2026-02-17",
    title: "fix: resolve netlify production build type errors",
    description: "Code updates shipped in commit b146273.",
  },
  {
    date: "Feb 17",
    sortDate: "2026-02-17",
    title: "docs: streamline agent routing and simplify repository documentation",
    description: "Code updates shipped in commit 32c93c0.",
  },
  {
    date: "Feb 17",
    sortDate: "2026-02-17",
    title: "chore: simplify docs and align app behavior updates",
    description: "Code updates shipped in commit 49c6f80.",
  },
  {
    date: "Feb 17",
    sortDate: "2026-02-17",
    title: "Polish sidebar comment and sign out action styling",
    description: "Code updates shipped in commit 930df8f.",
  },
  {
    date: "Feb 17",
    sortDate: "2026-02-17",
    title: "Include own student profile in friend profiles query",
    description: "Code updates shipped in commit c2e0e72.",
  },
  {
    date: "Feb 14",
    sortDate: "2026-02-14",
    title: "Add admin sprint student goal insights dashboard",
    description: "Code updates shipped in commit 1b927a2.",
  },
  {
    date: "Feb 13",
    sortDate: "2026-02-13",
    title: "Refine Viva Queue empty states for clearer layout",
    description: "Code updates shipped in commit 497414a.",
  },
  {
    date: "Feb 13",
    sortDate: "2026-02-13",
    title: "Improve Viva review clarity and attempts metrics",
    description: "Code updates shipped in commit 1bd06ae.",
  },
  {
    date: "Feb 13",
    sortDate: "2026-02-13",
    title: "Fix student comment widget overlap across pages",
    description: "Code updates shipped in commit 9ed1870.",
  },
  {
    date: "Feb 13",
    sortDate: "2026-02-13",
    title: "Automate in-app What's New from git history",
    description: "Code updates shipped in commit bb8ca1f.",
  },
  {
    date: "Feb 13",
    sortDate: "2026-02-13",
    title: "Add viva batch toggle and friend GIF expansion in settings",
    description: "Code updates shipped in commit 63fd321.",
  },
  {
    date: "Feb 12",
    sortDate: "2026-02-12",
    title: "Refine diagnostic question flow and last-question skip",
    description: "Code updates shipped in commit e6e1ed1.",
  },
  {
    date: "Feb 12",
    sortDate: "2026-02-12",
    title: "Improve diagnostic review clarity and add question skip flow",
    description: "Code updates shipped in commit 770c5c7.",
  },
  {
    date: "Feb 12",
    sortDate: "2026-02-12",
    title: "Require Diagnostic V2 and redesign Viva Queue triage UX",
    description: "Code updates shipped in commit b4d0844.",
  },
  {
    date: "Feb 12",
    sortDate: "2026-02-12",
    title: "Improve comment modal image upload UX and remove title bar",
    description: "Code updates shipped in commit 1d80197.",
  },
  {
    date: "Feb 12",
    sortDate: "2026-02-12",
    title: "Clean misconception tooling artifacts and document rewrite workflow",
    description: "Code updates shipped in commit cde1d22.",
  },
  {
    date: "Feb 12",
    sortDate: "2026-02-12",
    title: "Finalize warm misconception feedback and diagnostic tone",
    description: "Code updates shipped in commit fa52f86.",
  },
  {
    date: "Feb 11",
    sortDate: "2026-02-11",
    title: "Normalize full misconception bank tone and formatting",
    description: "Code updates shipped in commit 07fcfa6.",
  },
  {
    date: "Feb 11",
    sortDate: "2026-02-11",
    title: "Polish rollback misconception tone and extend sync audit",
    description: "Code updates shipped in commit 443cd84.",
  },
  {
    date: "Feb 11",
    sortDate: "2026-02-11",
    title: "Harden misconception sync with strict matching and rollback",
    description: "Code updates shipped in commit ed0708d.",
  },
  {
    date: "Feb 11",
    sortDate: "2026-02-11",
    title: "Implement character system updates and disable student XP flow",
    description: "Code updates shipped in commit 766efa0.",
  },
  {
    date: "Feb 9",
    sortDate: "2026-02-09",
    title: "fix: allow data image profile photo URLs",
    description: "Code updates shipped in commit c4437db.",
  },
  {
    date: "Feb 6",
    sortDate: "2026-02-06",
    title: "fix: show avatar image in sidebar when user has avatarUrl set",
    description: "Code updates shipped in commit 57bd83b.",
  },
  {
    date: "Feb 6",
    sortDate: "2026-02-06",
    title: "feat: add settings pages, credential management, and project link editing",
    description: "- Settings page for students (avatar, username, password)",
  },
  {
    date: "Feb 4",
    sortDate: "2026-02-04",
    title: "feat: add sprint history view with week navigation and goal import",
    description: "Browse previous sprints in read-only mode via a sprint selector dropdown.",
  },
  {
    date: "Feb 4",
    sortDate: "2026-02-04",
    title: "fix: exclude test setup dir from build tsconfig",
    description: "Code updates shipped in commit 8cb64f6.",
  },
  {
    date: "Feb 4",
    sortDate: "2026-02-04",
    title: "chore: bump convex to 1.31.7, add storage polyfill for tests",
    description: "Code updates shipped in commit e7fae9f.",
  },
];

export default WHATS_NEW;
